server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: serie-service
  config:
    import: optional:configserver:http://localhost:8888
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      host: localhost
      database: test
      port: 27017
rabbitmq:
  username: guest
  password: guest
  addresses:
   localhost: 5672
zipkin:
  base-url: http://localhost:9411
  sender:
    type: rabbit
  enabled: true
sleuth:
  sampler:
  probability: 1.0

message: Welcome!