server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: movie-service
  config:
    import: optional:configserver:http://localhost:8888
rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5672
zipkin:
  base-url: http://localhost:9411/
  sender:
    type: rabbit
    enabled: true
sleuth:
  sampler:
  probability: 1.0
queue:
  movie:
    name: TestQueue

message: Welcome!